#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([4.98394547e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.79972331e-310, 2.42383390e-052, 1.14195039e-071, 6.81854981e-091,
       1.74080801e+184, 6.79976756e-310])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x = np.empty(10)
x[5] = 1

print(x)

[4.98394547e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 6.79972331e-310 1.00000000e+000 1.14195039e-071 6.81854981e-091
 1.74080801e+184 6.79976756e-310]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
x = np.arange(10,49)


print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x = np.arange(10,49)

print(x[::-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(9).reshape(3,3)

print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

In [ ]:
x = np.array([1, 2, 0, 0, 4, 0])

for i in range(len(x)):
    if x[i] != 0:
        print(i)


0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
x = np.zeros((3,3))

for i in range(len(x)):
    for j in range(len(x)):
        if i-j == 0:
            x[i,j]=1

print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
x = np.zeros((3,3))

x[0,0]=1
x[1,1]=1
x[2,2]=1


print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
x = np.random.randint(0,10,27).reshape(3,3,3)

print(x)

[[[8 6 7]
  [4 9 0]
  [6 9 2]]

 [[1 2 6]
  [1 5 6]
  [9 5 4]]

 [[8 9 2]
  [6 8 2]
  [4 3 1]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np

x = np.random.randint(0,100,100).reshape(10,10)


print(x)

print("The Maximum value:" , np.max(x))
print("The Minimum value:" ,np.min(x))

[[17 67 23  3 48 76 40 66 18 40]
 [ 5 61 27  6 15 69 77 76 91 71]
 [ 6 42 20 30 19 59 40 49  5 51]
 [50 15 82 13 92 63  6 69 11 89]
 [64 63 41 39 52 50 33 55 48 63]
 [ 0 57 78  0 87 53 50 39 31  5]
 [22 83 35 61 85 42 99 17 84 70]
 [84  2 98 65 26 76  5 55 53 20]
 [ 1 88 58 20  1 31  9 69 57 76]
 [43 37 96 62 22 95 43 17 52 13]]
The Maximum value: 99
The Minimum value: 0


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
x = np.random.randint(0, 100, 30)

print(x)

print("The Mean:", np.mean(x))


[75 34  5 37 20 92 44  2 34 96 80  0  1 55  1 98 16 97 24 40 39 96 45 44
 78 83 35 26 44 27]
The Mean: 45.6


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print (np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
x = np.zeros((5,5))

count = 1
for i in range(1 , len(x)):
    for j in range(len(x)):
        if i-j == 0:
            x[i,j]=count
            count+=1

print(x)



[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
matrix =np.zeros((8,8))
matrix[1::2,::2]=1
# matrix[::2,1::2]=1
print (matrix)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np

N = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(N, (4,4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
x = np.random.rand(25).reshape(5,5)

print(x)

[[0.82544851 0.05859942 0.94460491 0.68600407 0.19073881]
 [0.12810625 0.6807427  0.78740996 0.74384289 0.65970665]
 [0.54528157 0.46842024 0.79057431 0.2769446  0.4965382 ]
 [0.03771075 0.40705839 0.40394205 0.67644619 0.73896697]
 [0.41544327 0.2452666  0.38408532 0.12981331 0.91857707]]


In [ ]:
x = np.random.random((5,5)).reshape(5,5)

print(x)


[[0.18004568 0.37532001 0.3421323  0.40121457 0.12149939]
 [0.81082001 0.33940821 0.21281804 0.57925285 0.48756842]
 [0.45304453 0.96219011 0.3863945  0.90770133 0.57093202]
 [0.57963952 0.17245628 0.69589962 0.20427601 0.11036965]
 [0.7656992  0.87774596 0.81075348 0.18781964 0.46231188]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
rgba_dtype = np.dtype([
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8),
    ('A', np.uint8)
])
color = np.array((255, 0, 0, 128), dtype=rgba_dtype)
print(color['R'])
print(color['G'])
print(color['B'])
print(color['A'])

255
0
0
128


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.random.randint(0,100,(5,3)).reshape(5,3)

matrix2 = np.random.randint(0,100,(3,2)).reshape(3,2)

x = np.dot(matrix1,matrix2)

print(x)

[[ 6953 13217]
 [ 2740  6363]
 [ 2966  6352]
 [ 5533 11329]
 [ 4754  9505]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
v = np.random.randint(0,20,10)
print("The Orignal vector:",v)

for i in range(len((v))):
    if v[i] >= 3 and v[i] <= 8:
        v[i] = -v[i]

print("The vector after edit:",v)

The Orignal vector: [ 2  9  0 12 16 19  5 13 11 19]
The vector after edit: [ 2  9  0 12 16 19 -5 13 11 19]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np

Z = np.array([1, 6, 8, 5, 4, 3])

print(Z ** Z)

print((2 << Z) >> 2)

print(Z < -Z)

print(1j * Z)

print(Z / 1 / 1)

print((Z < Z) > Z)


[       1    46656 16777216     3125      256       27]
[  1  32 128  16   8   4]
[False False False False False False]
[0.+1.j 0.+6.j 0.+8.j 0.+5.j 0.+4.j 0.+3.j]
[1. 6. 8. 5. 4. 3.]
[False False False False False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-32-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-32-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np

array_a = np.array([1.2, 2.7, -3.4, -4.9, 5.5], dtype=int)
print(array_a)


[ 1  2 -3 -4  5]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

v1 = np.array([1,2,3,4,5])
v2 = np.array([4,5,6,7])
v3 = np.array([])

for i in range(len(v1)):
    if v1[i] in v2:
        v3 = np.append(v3, v1[i])

print(v3)

[4. 5.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings

warnings.filterwarnings('ignore')

warnings.warn('Error: A warning just appeared')


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import numpy as np

print("Yesterday  is:",np.datetime64('today', 'D') - np.timedelta64(1,'D'))
print("Today is:",np.datetime64('today', 'D'))
print("Tomorrow is:",np.datetime64('today', 'D') + np.timedelta64(1,'D'))


Yesterday  is: 2023-09-27
Today is: 2023-09-28
Tomorrow is: 2023-09-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np

v = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v)



['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np
A = np.array([1, 7, 8, 4])
B = np.array([7, 9, 5, 4])

sum = A + B

multi = (A * -1) / 2
result = sum * multi

print(result)



[ -4. -56. -52. -16.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
import numpy as np

v = np.array([10.1 , 20.2 , 30.3 , 40.4, 8.6])

print("First Method:", np.floor(v))
print("Second Method:", v.astype(int))
print("Third Method:", np.trunc(v))
print("Forth Method:", np.ceil(v)-1)

First Method: [10. 20. 30. 40.  8.]
Second Method: [10 20 30 40  8]
Third Method: [10. 20. 30. 40.  8.]
Forth Method: [10. 20. 30. 40.  8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np
x = np.zeros((5,5))

x += np.arange(5)
print(x)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np

def generator():
    x = np.random.randint(0,20,10)
    return x

v = np.array(generator())

print(v)

[14  7 15 18 11  5 10 16  9  2]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np

v = np.random.uniform(0.0,1.0,10)

print(v)

[0.52126402 0.39987985 0.49037624 0.43099423 0.44590065 0.31315782
 0.2879812  0.08405971 0.17806744 0.01717455]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np

v = np.random.random(10)
print(v)
v = np.sort(v)
print(v)


[0.36579341 0.68427943 0.64259836 0.08558925 0.71664066 0.10696651
 0.1536365  0.73560144 0.82212694 0.6035493 ]
[0.08558925 0.10696651 0.1536365  0.36579341 0.6035493  0.64259836
 0.68427943 0.71664066 0.73560144 0.82212694]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import numpy as np

v = np.array([10,20,30])

print(np.sum(v))


60


In [ ]:
print(np.add.reduce(v))

60


In [ ]:
count = 0
for i in range(len(v)):
    count+= v[i]

print(count)

60


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np

A = np.random.randint(0,20,5)

B = np.random.randint(0,20,5)

print("A is:",A)
print()
print("B is:",B)
print()

if np.array_equal(A,B):
    print("Array A and B Equal")
else:
    print("Array A and B Not Equal")

A is: [10 14 12 18 19]

B is: [19 19 17 12  7]

Array A and B Not Equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np


x = np.array([10,20,30])


x.flags.writeable = False

#x[0]=1
print(x)

[10 20 30]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np


x = np.random.randint(0,10,10)

print("Orignal Array:",x)
print("Maximum value is:" , np.max(x))

for i in range(len(x)):
    if x[i] == np.max(x):
        x[i] = 0

print("Modified Array:",x)

Orignal Array: [9 4 0 1 0 0 3 2 2 9]
Maximum value is: 9
Modified Array: [0 4 0 1 0 0 3 2 2 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np

dtype = [('x', float), ('y', float)]
structured_array = np.zeros((5, 5), dtype=dtype)

x_values = np.linspace(0, 1, 5)
y_values = np.linspace(0, 1, 5)

structured_array['x'], structured_array['y'] = np.meshgrid(x_values, y_values)

print(structured_array)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])


C = np.ones((len(X), len(Y)))

for i in range(len(X)):
    for j in range(len(Y)):
        C[i, j] = 1 / (X[i] - Y[j])

print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
x = np.array([10,20,30])

print(x)

[10 20 30]


In [ ]:
x = np.array([10,20,30])

for i in range(len(x)):
  print(x[i])

10
20
30


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import numpy as np

np.random.seed(5)
coordinates = np.random.rand(5, 2)

x , y = np.meshgrid( coordinates[:, 0],  coordinates[:, 1])

distances = np.sqrt((x - x.T)**2 + (y - y.T)**2)

print(distances)


[[0.         0.05025591 0.37155561 0.64804982 0.68709553]
 [0.05025591 0.         0.41655466 0.68763826 0.73641997]
 [0.37155561 0.41655466 0.         0.29276974 0.46530619]
 [0.64804982 0.68763826 0.29276974 0.         0.57395301]
 [0.68709553 0.73641997 0.46530619 0.57395301 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
array_a = np.array([1.5,2.2,3.6], dtype = np.int32)
array_a

array([1, 2, 3], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np

file_path = r'test.csv'

def custom_converter(x):
    return np.nan if x.strip() == '' else float(x)

matrix = np.genfromtxt(file_path, delimiter=',', converters={i: custom_converter for i in range(5)})


print(matrix)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [ ]:
import numpy as np

file_path = 'test.csv'

matrix = np.genfromtxt(file_path, delimiter=',')
matrix[np.isnan(matrix)] = np.nan

print(matrix)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [91]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

result_matrix = matrix - row_means

print("Subtracting Row Means:")
print(result_matrix)


Subtracting Row Means:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [101]:
import numpy as np

matrix = np.array([
    [5, 2, 9],
    [1, 8, 3],
    [7, 4, 6]])

n = int(input("Enter Index of coloumn you want to sort by: "))

print(f"Sort the said array by the {n}th column: ")
print(matrix[matrix[:,n].argsort()])


Enter Index of coloumn you want to sort by: 0
Sort the said array by the 0th column: 
[[1 8 3]
 [5 2 9]
 [7 4 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [87]:
import numpy as np

x = np.random.randint(0,3,(3,10)).astype(float)
x[:,0] = np.nan
G = np.isnan(x)
print((G.all(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np

arr = np.array([10, 16, 22, 35, 40])

given_value = 50

abs_diff = np.abs(arr - given_value)
nearest_index = (abs_diff).argmin()
nearest_value = arr[nearest_index]

print("Array:", arr)
print("Target Value:", given_value)
print("Nearest Value:", nearest_value)


Array: [10 16 22 35 40]
Target Value: 50
Nearest Value: 40


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
import numpy as np

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
sum= np.zeros((3,3))

print(A)
print(B)
print()

for i in range(len(A)):
    for j in range(len(B)):
        sum[i] = A[i]+B[j]

print(sum)

[[0]
 [1]
 [2]]
[[0 1 2]]

[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
import numpy as np

class NamedArray:
    def __init__(self, name, elements=[]):
        self.name = name
        self.elements = np.array(elements)

    def __str__(self):
        return f"{self.name}: {self.elements}"

arr = NamedArray("Array", [1, 2, 3])

print(arr)

Array: [1 2 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
import numpy as np


v = np.array([10, 20, 30, 40, 50])

for i in range(len(v)):
  v[i]+=1

print(v)


[11 21 31 41 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np

matrix = np.random.randint(0, 10, size=(4, 3, 2, 2))

summ = np.sum(matrix, axis=(2, 3))

print(summ)


[[13 21 28]
 [14  8 18]
 [21 15 15]
 [18 22 15]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.array([10,20,30,40,50])
print(np.mean(D))

30.0


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
import numpy as np

m1 = np.random.randint(0,10,(3,3))
m2 = np.random.randint(0,10,(3,3))

dotp = np.dot(m1 , m2)
print("dot product:")
print(dotp)
print()
print("The diagonal of a dot product:",dotp.diagonal())

dot product:
[[ 40  40 120]
 [ 10  10  58]
 [ 71  59 149]]

The diagonal of a dot product: [ 40  10 149]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
import numpy as np
nums = np.array([1, 2, 3, 4, 5])
print("Original array:")
print(nums)

new_nums = np.zeros(len(nums) + (len(nums)-1)*(3))
new_nums[::4] = nums

print("\nNew array:")
print(new_nums)


Original array:
[1 2 3 4 5]

New array:
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)